<?php
/*
* Support Dynamo Report email template
*/

global $support_options, $wpdb;

$total_emailtix = dynamo_support_tickets_by_email();
$total_system = dynamo_support_total_tickets()-$emailtix;

$emailreply = dynamo_support_replys_by_email();
$replysystem = dynamo_support_total_replys()-$emailreply;

//Recent Searches
$searches = $support_options['kb_searches']; 
if(is_array($searches) && count($searches) > 0) {
	$search = '<tr>
				<th><strong>Search Term</strong></th>
			  </tr>';
	foreach(array_reverse($searches) as $s) {	
		$search .= '<tr>
						<td>'.$s.'</td>
					</tr>';
	 } 
} else { 
		$search = ' <tr>
						<td>No recent search terms found</td>
					</tr>';
} 
//Most Viewed
$postmeta = $wpdb->prefix.'postmeta'; 
$posts = $wpdb->prefix.'posts'; 
$views = $wpdb->get_results("SELECT meta.post_id, posts.post_title, meta.meta_value AS views
							FROM $postmeta meta
							INNER JOIN $posts posts ON ( meta.post_id = posts.ID )
							WHERE meta.meta_key = 'kb_views'
							ORDER BY views DESC
							LIMIT 0 , 30");
							
							
							
if(is_array($views) && count($views) > 0) {
//Sort By Views
$views = sortArrayofObjectByProperty( $views, 'views' );
$views = array_reverse($views); 


		$viewed = '<tr>
					<th><strong>Article</strong></th><th><strong>Views</strong></th>
					</tr>';
	foreach($views as $v) { 
		$viewed .= '<tr>
						<td><a href="'.get_permalink($v->post_id).'" title="Edit" target="_blank">'.$v->post_title.'</a></td><td>'.$v->views.'</td>
					</tr>';
	}
} else { 
		$viewed =	'<tr>
						<td>No knowledge base views</td>
					</tr>';
} 							

$content = '
<div style="width:500px; margin: 0 auto;">
	<h2>Support Dynamo - Weekly Report</h2>
	<p style="margin-top:1px;">Support Dynamo ~ The Complete WordPress Help Desk & Customer Interaction Manager<br/>Here is a quick look at your support totals.</p>
	<h3 style="margin-bottom:2px;">All Time Total Stats</h3>
	<p style="margin-top:1px;">Below you will see the total support stats.</p>
	<table style="margin-left:15px;">
		<tr>
			<td>Total Questions:</td>
			<td><strong>'.dynamo_support_total_tickets().'</strong></td>
		</tr>
		<tr>
			<td>Total Questions By Email:</td>
			<td><strong>'.$total_emailtix.'</strong></td>
		</tr>
		<tr>
			<td>Total Questions Through System:</td>
			<td><strong>'.$total_system.'</strong></td>
		</tr>
		<tr>
			<td>Total Question Replies:</td>
			<td><strong>'.dynamo_support_total_replys().'</strong></td>
		</tr>
		<tr>
			<td>Total Question Replies By Email:</td>
			<td><strong>'.$emailreply.'</strong></td>
		</tr>
		<tr>
			<td>Total Question Replies Through System:</td>
			<td><strong>'.$replysystem.'</strong></td>
		</tr>
	</table>
	<h3 style="margin-bottom:2px;">Knowledge Base Stats</h3>
	<p style="margin-top:1px;">Below you will see stats for your knowledge base for your most viewed and most recent searches.</p>
	<h4 style="margin-bottom:2px;">Recent Knowledge Base Searches</h4>
	<table style="margin-left:15px;">
		'.$search.'
	</table>
	<h4 style="margin-bottom:2px;">Recent Knowledge Base Activity:</h4>	
	<table style="margin-left:15px;">
		'.$viewed.'
	</table>
	<p style="margin-top:20px;"><small>This e-mail was auto generated by Support Dynamo, a WordPress Plugin by <a href="http://plugindynamo.com">plugindynamo.com</a>. To stop receiving this e-mail disable the send weekly e-mail report check-box in the Support Dynamo settings tab on your WordPress site.</small></p>
</div>';
?>