<?php
//Expired email content template
$content = '
<div style="width:500px; margin: 0 auto;">
	<strong style="font-size:18px;">Oops.. It looks like your Support Dynamo PluginDynamo.com account has expired!</strong><br/><br/>
	<a href="http://plugindynamo.com/account-activations-support-dynamo" target="_blank" title="Renew Your Account" rel="">Click Here To Renew Your Account &#187;</a><br/><span style="font-size:10px;">or copy & paste this url in to your browser: http://plugindynamo.com/account-activations-support-dynamo </span>
	<p><strong>Note:</strong> If you believe you are seeing this message in error and know that your Support Dynamo PluginDynamo.com account is still active and in good standing, ensure you have entered the correct e-mail associated with your PluginDynamo.com account on the "Account" tab in the Support Dynamo options.
	<br/><br/>
	If this fails, please submit a support ticket to <a href="mailto:support@plugindynamo.com" title="Contact PluginDynamo.com Support"><strong>Support@PluginDynamo.com</strong></a> from the e-mail address associated with your account or login to your PluginDynamo.com account and click on the Support link.</p>
	<a href="http://plugindynamo.com/account-activations-support-dynamo" target="_blank" title="Renew Your Account" rel="">Click Here To Renew Your Account &#187;</a><br/> <span style="font-size:10px;">or copy & paste this url in to your browser: http://plugindynamo.com/account-activations-support-dynamo </span>
	<p style="margin-top:20px;"><small>This e-mail was auto generated by Support Dynamo, a WordPress Plugin by <a href="http://plugindynamo.com">plugindynamo.com</a>. To stop receiving this e-mail disable the send weekly e-mail report check-box in the Support Dynamo settings tab on your WordPress site.</small></p>
</div>';
?>